# Generated by Django 2.2.2 on 2019-06-24 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Apropriacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('referenciaApropriacao', models.DateTimeField()),
                ('horas', models.DurationField()),
                ('descricao', models.CharField(max_length=2048)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='input.Colaborador')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='input.Projeto')),
            ],
        ),
    ]
