# Generated by Django 2.2.2 on 2019-07-11 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apropriacao',
            old_name='horas',
            new_name='duracao',
        ),
        migrations.RenameField(
            model_name='apropriacao',
            old_name='referenciaApropriacao',
            new_name='referencia',
        ),
    ]
