# Generated by Django 2.2.2 on 2019-07-11 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_auto_20190711_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apropriacao',
            name='duracao',
            field=models.DurationField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
