# Generated by Django 2.2.2 on 2019-07-11 20:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_auto_20190711_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apropriacao',
            name='duracao',
            field=models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(0)), django.core.validators.MaxValueValidator(datetime.timedelta(0, 86340))]),
        ),
    ]
